### ISSUE TITLE
Paragraph following a list

### ISSUE THREAD

**Issue by tombentley** [rohitmohan96/ceylon.markdown#11]
Not sure if it's already covered by one of the other list-related bugs but it seems that this markdow

```
* blah
* blah

foo
```

is not rendered properly -- foo should be in a paragraph following the unordered list, not merged into the last item of the list.

**Comment by rohitmohan96** [comment]
This should be fixed in 52fbb38b63f4f036a7df1da8ddf6a020ef3672b8. Closing for now.
