### ISSUE TITLE
make parse() function thread safe

### ISSUE THREAD

**Issue by jvasileff** [rohitmohan96/ceylon.markdown#13]
Parsing currently uses a mutable global map, which will cause problems if there is more then one simultaneous invocation of `parse()`.

See https://github.com/rohitmohan96/ceylon.markdown/blob/c044dddc9b9b8213a8701df2b3e0774be5e30607/source/ceylon/markdown/core/parse.ceylon#L5

**Comment by rohitmohan96** [comment]
I have removed the global variables and made them parameters. That should fix this right?

**Comment by jvasileff** [comment]
That looks good to me. Thanks!

**Comment by rohitmohan96** [comment]
Closing for now.
