### ISSUE TITLE
Link references not working

### ISSUE THREAD

**Issue by FroMage** [rohitmohan96/ceylon.markdown#7]
http://spec.commonmark.org/0.26/#reference-link

This means I can't use `ceylon.markdown` to render its own `README.md` file ;)

```
[This project][source] contains a Markdown processor

...

Some js tests do not pass (#4) [source]: https://github.com/rohitmohan96/ceylon.markdown/tree/master/ [spec]: http://spec.commonmark.org/0.26/ [commits]: https://github.com/rohitmohan96/ceylon.markdown/commits/master?author=rohitmohan96
```

**Comment by rohitmohan96** [comment]
Yes, this is because of #3.

**Comment by FroMage** [comment]
Oh, sorry, I didn't think it was related. You're right, if I insert a paragraph it works, closing.

**Comment by rohitmohan96** [comment]
A newline before `[source]:` should work.
